import type { PromptPreset } from "./promptBlockTypes";

export const PROMPT_PRESETS: PromptPreset[] = [
  {
    id: "cinematic-3-frame-film-stills",
    label: "Cinematic 3-frame film stills",
    description: "Chronological wide / medium / close cinematic sequence.",
    defaultMode: "consecutive",
    blockIds: [
      "source-uploaded-image-primary",
      "subject-preserve-identity",
      "frame-vertical-triptych",
      "structure-wide-medium-close",
      "logic-consecutive-sequence",
      "action-natural-walk",
      "style-prestige-drama",
      "texture-35mm-film",
      "lighting-cool-natural-contrast",
      "continuity-subject-environment",
      "negative-common-artifacts",
      "output-copy-ready",
    ],
    tags: ["film", "storyboard", "consecutive"],
  },
  {
    id: "same-moment-concurrent-triptych",
    label: "Same-moment concurrent triptych",
    description: "Three different vantages of one frozen instant.",
    defaultMode: "concurrent",
    blockIds: [
      "source-uploaded-image-primary",
      "subject-preserve-identity",
      "frame-vertical-triptych",
      "structure-wide-medium-close",
      "logic-concurrent-same-instant",
      "moment-frozen-action-state",
      "style-prestige-drama",
      "texture-35mm-film",
      "lighting-cool-natural-contrast",
      "continuity-subject-environment",
      "negative-common-artifacts",
      "output-copy-ready",
    ],
    tags: ["triptych", "concurrent", "multi-camera"],
  },
  {
    id: "noir-atmosphere-conversion",
    label: "Noir atmosphere conversion",
    description: "Cool, shadow-heavy noir treatment with cinematic continuity.",
    defaultMode: "consecutive",
    blockIds: [
      "source-uploaded-image-primary",
      "subject-preserve-identity",
      "frame-vertical-triptych",
      "structure-wide-medium-close",
      "logic-consecutive-sequence",
      "camera-foreground-framing",
      "action-natural-walk",
      "style-moody-noir",
      "texture-35mm-film",
      "lighting-cool-natural-contrast",
      "continuity-subject-environment",
      "negative-common-artifacts",
      "output-copy-ready",
    ],
    tags: ["noir", "consecutive", "cinematic"],
  },
  {
    id: "front-side-rear-reference",
    label: "Front / side / rear technical reference",
    description: "Concurrent same-moment subject coverage from three vantages.",
    defaultMode: "concurrent",
    blockIds: [
      "source-uploaded-image-primary",
      "subject-preserve-identity",
      "frame-vertical-triptych",
      "logic-concurrent-same-instant",
      "moment-frozen-action-state",
      "continuity-subject-environment",
      "negative-common-artifacts",
      "output-copy-ready",
    ],
    tags: ["reference", "technical", "concurrent"],
  },
];
