import type { PromptBlock } from "./promptBlockTypes";

export const STRUCTURE_GUIDE = [
  "Source Fidelity",
  "Subject / Scene",
  "Composition",
  "Shot Structure",
  "Consecutive or Concurrent Logic",
  "Camera / Vantage Details",
  "Action or Moment",
  "Style",
  "Lighting / Atmosphere",
  "Technical Rendering",
  "Continuity Rules",
  "Negative Instructions",
  "Output Requirements",
] as const;

export const PROMPT_BLOCKS: PromptBlock[] = [
  {
    id: "source-uploaded-image-primary",
    label: "Uploaded Image as Primary Reference",
    category: "source-fidelity",
    description: "Preserve the uploaded image as the source of truth.",
    promptText:
      "Use the uploaded image as the primary visual reference for the subject, outfit, pose language, environment, lighting logic, background details, and spatial continuity.",
    modeCompatibility: "both",
    defaultEnabled: true,
    required: true,
    sortOrder: 10,
    tags: ["source", "uploaded-image", "fidelity"],
    negativePromptCompatible: false,
    exampleUse: "Photo transformation prompts that must keep the original subject recognizable.",
    priority: 100,
    weight: 1,
    supportsShotNumber: false,
    supportsVantage: false,
    supportsTimeline: false,
    supportsSameMomentContinuity: true,
  },
  {
    id: "subject-preserve-identity",
    label: "Preserve Subject Identity",
    category: "source-fidelity",
    description: "Keeps the subject consistent across frames.",
    promptText:
      "Preserve the subject's recognizable identity, facial structure, hairstyle, outfit, accessories, body proportions, and natural posture across every frame.",
    modeCompatibility: "both",
    defaultEnabled: true,
    required: true,
    sortOrder: 20,
    tags: ["identity", "continuity"],
    negativePromptCompatible: false,
    exampleUse: "Sequential images, triptychs, style transformations.",
    priority: 100,
    weight: 1,
    supportsShotNumber: false,
    supportsVantage: false,
    supportsTimeline: false,
    supportsSameMomentContinuity: true,
  },
  {
    id: "frame-vertical-triptych",
    label: "Vertical Triptych",
    category: "shot-structure",
    description: "Three horizontal frames stacked vertically.",
    promptText:
      "Create a vertical cinematic triptych made of three horizontal film stills stacked vertically, full bleed edge-to-edge, with no borders, captions, labels, or text.",
    modeCompatibility: "both",
    defaultEnabled: true,
    required: false,
    sortOrder: 100,
    tags: ["triptych", "three-frame", "vertical"],
    negativePromptCompatible: false,
    exampleUse: "Three-panel cinematic image prompts.",
    priority: 80,
    weight: 1,
    supportsShotNumber: true,
    supportsVantage: true,
    supportsTimeline: true,
    supportsSameMomentContinuity: true,
  },
  {
    id: "structure-wide-medium-close",
    label: "Wide / Medium / Close Coverage",
    category: "shot-structure",
    description: "Classic cinematic coverage structure.",
    promptText:
      "Use a wide establishing frame, a medium tracking-style frame, and a closer candid frame to create clear visual variety and cinematic coverage.",
    modeCompatibility: "both",
    defaultEnabled: true,
    required: false,
    sortOrder: 120,
    tags: ["coverage", "wide", "medium", "close"],
    negativePromptCompatible: false,
    exampleUse: "Film still prompts and multi-camera viewpoint arrays.",
    priority: 70,
    weight: 1,
    supportsShotNumber: true,
    supportsVantage: true,
    supportsTimeline: true,
    supportsSameMomentContinuity: true,
  },
  {
    id: "logic-consecutive-sequence",
    label: "Consecutive Chronological Logic",
    category: "logic",
    description: "Frames happen one after another.",
    promptText:
      "Treat the frames as consecutive moments in chronological order. Frame 1 begins the action, Frame 2 continues the movement, and Frame 3 concludes with a quieter ending beat.",
    modeCompatibility: "consecutive",
    defaultEnabled: true,
    required: false,
    sortOrder: 200,
    tags: ["consecutive", "timeline", "chronological"],
    negativePromptCompatible: false,
    exampleUse: "Storyboards, motion sequences, before/during/after transformations.",
    priority: 90,
    weight: 1,
    supportsShotNumber: true,
    supportsVantage: false,
    supportsTimeline: true,
    supportsSameMomentContinuity: false,
  },
  {
    id: "logic-concurrent-same-instant",
    label: "Concurrent Same-Instant Logic",
    category: "logic",
    description: "Frames show the same instant from different vantages.",
    promptText:
      "Treat all frames as simultaneous views of the exact same instant. Show one frozen moment from separate camera vantages with identical subject pose, action state, lighting conditions, wardrobe, environment, and scene continuity. Do not imply time progression.",
    modeCompatibility: "concurrent",
    defaultEnabled: true,
    required: false,
    sortOrder: 200,
    tags: ["concurrent", "same-instant", "multi-camera"],
    negativePromptCompatible: false,
    exampleUse: "Same-moment triptychs, reference sheets, multi-vantage reconstructions.",
    priority: 90,
    weight: 1,
    supportsShotNumber: true,
    supportsVantage: true,
    supportsTimeline: false,
    supportsSameMomentContinuity: true,
  },
  {
    id: "action-natural-walk",
    label: "Natural Walk",
    category: "action-moment",
    description: "Natural walking motion.",
    promptText:
      "The subject should move naturally through the scene with relaxed posture, believable stride, subtle arm movement, and candid body language.",
    modeCompatibility: "consecutive",
    defaultEnabled: true,
    required: false,
    sortOrder: 300,
    tags: ["walk", "motion", "candid"],
    negativePromptCompatible: false,
    exampleUse: "Walking storyboard or film still progression.",
    priority: 60,
    weight: 1,
    supportsShotNumber: false,
    supportsVantage: false,
    supportsTimeline: true,
    supportsSameMomentContinuity: false,
  },
  {
    id: "moment-frozen-action-state",
    label: "Frozen Action State",
    category: "action-moment",
    description: "Same action state for all concurrent views.",
    promptText:
      "Keep the subject in the same pose and action state across all frames, changing only the camera vantage, framing distance, and lens perspective.",
    modeCompatibility: "concurrent",
    defaultEnabled: true,
    required: false,
    sortOrder: 300,
    tags: ["frozen", "same-action", "multi-view"],
    negativePromptCompatible: false,
    exampleUse: "Concurrent triptychs or continuity sheets.",
    priority: 70,
    weight: 1,
    supportsShotNumber: false,
    supportsVantage: true,
    supportsTimeline: false,
    supportsSameMomentContinuity: true,
  },
  {
    id: "camera-foreground-framing",
    label: "Foreground Framing",
    category: "camera-vantage",
    description: "Adds depth through foreground elements.",
    promptText:
      "Use foreground elements such as leaves, shadows, railings, reflections, or environmental shapes to partially frame at least one shot while keeping the subject visible.",
    modeCompatibility: "both",
    defaultEnabled: false,
    required: false,
    sortOrder: 400,
    tags: ["foreground", "depth", "camera"],
    negativePromptCompatible: false,
    exampleUse: "Noir, documentary, or cinematic prompts.",
    priority: 40,
    weight: 0.8,
    supportsShotNumber: true,
    supportsVantage: true,
    supportsTimeline: true,
    supportsSameMomentContinuity: true,
  },
  {
    id: "style-moody-noir",
    label: "Moody Noir",
    category: "style",
    description: "Cool, shadow-heavy noir treatment.",
    promptText:
      "Apply a moody noir cinematic style with cool blue-black shadows, strong contrast, deep-space blacks, restrained highlights, reflective details, and realistic skin tones.",
    modeCompatibility: "both",
    defaultEnabled: false,
    required: false,
    sortOrder: 500,
    tags: ["noir", "cool", "high-contrast"],
    negativePromptCompatible: false,
    exampleUse: "Noir atmosphere conversions.",
    priority: 50,
    weight: 1,
    supportsShotNumber: false,
    supportsVantage: false,
    supportsTimeline: false,
    supportsSameMomentContinuity: true,
  },
  {
    id: "style-warm-90s",
    label: "Warm 90s Vacation Nostalgia",
    category: "style",
    description: "Sun-washed nostalgic vacation film look.",
    promptText:
      "Apply a warm 1990s vacation film style with sun-washed highlights, slightly faded colors, soft contrast, mild overexposure in bright areas, warm natural skin tones, and nostalgic color shifts.",
    modeCompatibility: "both",
    defaultEnabled: false,
    required: false,
    sortOrder: 510,
    tags: ["90s", "vacation", "nostalgia"],
    negativePromptCompatible: false,
    exampleUse: "Summer memory transformations.",
    priority: 50,
    weight: 1,
    supportsShotNumber: false,
    supportsVantage: false,
    supportsTimeline: false,
    supportsSameMomentContinuity: true,
  },
  {
    id: "style-prestige-drama",
    label: "Prestige Streaming Drama",
    category: "style",
    description: "Polished character-drama realism.",
    promptText:
      "Apply a prestige streaming drama look with cool natural color grading, restrained saturation, rich contrast, deep realistic blacks, cinematic depth, subtle lens bloom, and emotionally grounded realism.",
    modeCompatibility: "both",
    defaultEnabled: false,
    required: false,
    sortOrder: 520,
    tags: ["prestige", "drama", "cinematic"],
    negativePromptCompatible: false,
    exampleUse: "Character-driven cinematic prompt transformations.",
    priority: 50,
    weight: 1,
    supportsShotNumber: false,
    supportsVantage: false,
    supportsTimeline: false,
    supportsSameMomentContinuity: true,
  },
  {
    id: "style-music-video-cool",
    label: "Music-Video Cool",
    category: "style",
    description: "Glossy, rhythmic modern styling.",
    promptText:
      "Apply a modern music-video cinematic style with cool cyan shadows, deep blacks, punchy contrast, crisp highlights, reflective shimmer, controlled bloom, and stylish rhythmic energy.",
    modeCompatibility: "both",
    defaultEnabled: false,
    required: false,
    sortOrder: 530,
    tags: ["music-video", "gloss", "energy"],
    negativePromptCompatible: false,
    exampleUse: "Stylized high-energy image transformations.",
    priority: 50,
    weight: 1,
    supportsShotNumber: false,
    supportsVantage: false,
    supportsTimeline: false,
    supportsSameMomentContinuity: true,
  },
  {
    id: "style-documentary-realism",
    label: "Documentary Realism",
    category: "style",
    description: "Raw, truthful documentary treatment.",
    promptText:
      "Apply a raw documentary realism style with natural cool color grading, believable contrast, authentic skin tones, imperfect focus, mild motion blur, subtle grain, uneven exposure, and organic photographic texture.",
    modeCompatibility: "both",
    defaultEnabled: false,
    required: false,
    sortOrder: 540,
    tags: ["documentary", "realism", "raw"],
    negativePromptCompatible: false,
    exampleUse: "Observational cinematic prompts.",
    priority: 50,
    weight: 1,
    supportsShotNumber: false,
    supportsVantage: false,
    supportsTimeline: false,
    supportsSameMomentContinuity: true,
  },
  {
    id: "style-soft-romantic-indie",
    label: "Soft Romantic Indie Film",
    category: "style",
    description: "Tender, poetic, memory-like indie tone.",
    promptText:
      "Apply a soft romantic indie film style with gentle cool tones, delicate highlights, softened contrast, natural skin tones, shallow depth of field, soft lens falloff, faint motion blur, subtle grain, and dreamy analog imperfections.",
    modeCompatibility: "both",
    defaultEnabled: false,
    required: false,
    sortOrder: 550,
    tags: ["indie", "romantic", "soft"],
    negativePromptCompatible: false,
    exampleUse: "Poetic and intimate image transformations.",
    priority: 50,
    weight: 1,
    supportsShotNumber: false,
    supportsVantage: false,
    supportsTimeline: false,
    supportsSameMomentContinuity: true,
  },
  {
    id: "texture-35mm-film",
    label: "35mm Film Texture",
    category: "technical-rendering",
    description: "Subtle analog film texture.",
    promptText:
      "Add fine 35mm film grain, faint halation, subtle lens softness, natural highlight rolloff, minor exposure inconsistencies, and organic color variation.",
    modeCompatibility: "both",
    defaultEnabled: true,
    required: false,
    sortOrder: 600,
    tags: ["35mm", "grain", "film"],
    negativePromptCompatible: false,
    exampleUse: "Cinematic film still prompts.",
    priority: 40,
    weight: 0.8,
    supportsShotNumber: false,
    supportsVantage: false,
    supportsTimeline: false,
    supportsSameMomentContinuity: true,
  },
  {
    id: "lighting-cool-natural-contrast",
    label: "Cool Natural Contrast",
    category: "lighting-atmosphere",
    description: "Grounded cinematic lighting.",
    promptText:
      "Use cool natural contrast with believable shadows, realistic skin tones, restrained highlights, and deep but not crushed blacks.",
    modeCompatibility: "both",
    defaultEnabled: true,
    required: false,
    sortOrder: 650,
    tags: ["lighting", "contrast", "natural"],
    negativePromptCompatible: false,
    exampleUse: "General cinematic image prompts.",
    priority: 40,
    weight: 0.8,
    supportsShotNumber: false,
    supportsVantage: false,
    supportsTimeline: false,
    supportsSameMomentContinuity: true,
  },
  {
    id: "continuity-subject-environment",
    label: "Subject and Environment Continuity",
    category: "continuity",
    description: "Keeps subject and setting coherent.",
    promptText:
      "Maintain consistent subject identity, wardrobe, accessories, body proportions, location, water feature, greenery, background objects, and spatial layout across every frame.",
    modeCompatibility: "both",
    defaultEnabled: true,
    required: true,
    sortOrder: 700,
    tags: ["continuity", "guardrail"],
    negativePromptCompatible: false,
    exampleUse: "All multi-frame prompts.",
    priority: 100,
    weight: 1,
    supportsShotNumber: false,
    supportsVantage: true,
    supportsTimeline: true,
    supportsSameMomentContinuity: true,
  },
  {
    id: "negative-common-artifacts",
    label: "Negative: Common Artifacts",
    category: "negative",
    description: "Avoids common image model failures.",
    promptText:
      "Do not add text, borders, captions, logos, watermarks, UI elements, duplicate subjects, unrelated backgrounds, extreme face changes, warped anatomy, extra limbs, broken hands, inconsistent clothing, plastic skin, cartoon styling, or fantasy lighting.",
    modeCompatibility: "both",
    defaultEnabled: true,
    required: false,
    sortOrder: 800,
    tags: ["negative", "guardrail", "quality"],
    negativePromptCompatible: true,
    exampleUse: "Negative prompt export.",
    priority: 80,
    weight: 1,
    supportsShotNumber: false,
    supportsVantage: false,
    supportsTimeline: false,
    supportsSameMomentContinuity: true,
  },
  {
    id: "output-copy-ready",
    label: "Copy-Ready Output",
    category: "output",
    description: "Keeps prompt ready for image tools.",
    promptText:
      "The final result should be photorealistic, cinematic, emotionally grounded, human-readable, and ready to paste into image generation tools.",
    modeCompatibility: "both",
    defaultEnabled: true,
    required: false,
    sortOrder: 900,
    tags: ["output", "copy-ready"],
    negativePromptCompatible: false,
    exampleUse: "Final line of compiled prompts.",
    priority: 50,
    weight: 1,
    supportsShotNumber: false,
    supportsVantage: false,
    supportsTimeline: false,
    supportsSameMomentContinuity: true,
  },
];

export const getBlocksByCategory = () =>
  PROMPT_BLOCKS.reduce<Record<string, PromptBlock[]>>((acc, block) => {
    acc[block.category] ||= [];
    acc[block.category].push(block);
    return acc;
  }, {});
